export const RETRIEVE_TRADE_LOGS_SUCCESS = "RETRIEVE_TRADE_LOGS_SUCCESS";
export const RETRIEVE_TRADE_LOGS_FAILURE = "RETRIEVE_TRADE_LOGS_FAILURE";

export const RETRIEVE_PRODUCTS_START = "RETRIEVE_PRODUCTS_START";
export const RETRIEVE_PRODUCTS_SUCCESS = "RETRIEVE_PRODUCTS_SUCCESS";
export const RETRIEVE_PRODUCTS_FAILURE = "RETRIEVE_PRODUCTS_FAILURE";

export const RETRIEVE_CARRIERS_START = "RETRIEVE_CARRIERS_START";
export const RETRIEVE_CARRIERS_SUCCESS = "RETRIEVE_CARRIERS_SUCCESS";
export const RETRIEVE_CARRIERS_FAILURE = "RETRIEVE_CARRIERS_FAILURE";

export const RETRIEVE_SHIPMENTS_START = "RETRIEVE_SHIPMENTS_START";
export const RETRIEVE_SHIPMENTS_SUCCESS = "RETRIEVE_SHIPMENTS_SUCCESS";
export const RETRIEVE_SHIPMENTS_FAILURE = "RETRIEVE_SHIPMENTS_FAILURE";

export const CREATE_SHIPMENT_START = "CREATE_SHIPMENT_START";
export const CREATE_SHIPMENT_SUCCESS = "CREATE_SHIPMENT_SUCCESS";
export const CREATE_SHIPMENT_FAILURE = "CREATE_SHIPMENT_FAILURE";

export const UPDATE_SHIPMENT_START = "UPDATE_SHIPMENT_START";
export const UPDATE_SHIPMENT_SUCCESS = "UPDATE_SHIPMENT_SUCCESS";
export const UPDATE_SHIPMENT_FAILURE = "UPDATE_SHIPMENT_FAILURE";
